# Generated by Django 5.2.1 on 2025-05-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'categories', 'verbose_name_plural': 'categories'},
        ),
    ]
